[default]
duration="30m"
mode="center"
sorting="random"

[any]
path = "~/Pictures/screenshot/walls"

# This is the name for the monitor I generally use
[DP-2]
path = "~/Pictures/screenshot/walls"

# This is the name for the laptop screen
[eDP-1]
path = "~/Pictures/screenshot/walls"

[default.transition.glitch-displace]
